T3574: add support for --grp argument
vyos/vyos-utils pull request #1
Opened 2021-06-08 21:32 UTC by jestabro

This PR (draft for the moment, pending discussion) adds support for grouping arguments with logical and. The parsing of arguments follows a 'natural order' without using demarcation of the arguments in a group, namely, all arguments following --grp (up until the next --grp) are joined by logical AND. Non-grouped arguments should precede the first --grp. All non-group arguments and all group arguments are joined by logical OR. If no --grp are present, behaviour is unchanged.

Making use of this feature in vyos-1x requires a companion PR, to be noted here ...

2021-06-09 14:18 UTC, dmbaturin requested changes
I like the overall idea. The CLI design seems sensible to me, and I don't think we can do better: non-group arguments followed by groups and groups separated by a special option is probably the best that the UNIX CLI framework allows.

I think the implementation can be improved though. I think the code will be easier to read if we split the implementation into phases:

* First, build a flat list of raw options (of type `RegexOpt of string | ExecOpt of string | GroupSeparator`.
* Second, convert it to a list of "check or check group values", like `type check = Regex of string | Exec of string | Group of check list` (it allows nested groups, but that's not an issue).
* Do validation using a recursive function with a special case for `Group`.

Since lists of validators are very small, there are no performance concerns there.

2021-06-09 14:18 UTC, dmbaturin commented on src/validate_value.ml
> +    List.fold_left (&&) true (List.map (fun e -> validate_value buf e value) conj_checks)
There's `List.for_all` function in the standard library that can come in handy here.

2021-06-09 14:28 UTC, jestabro commented on src/validate_value.ml
> +    List.fold_left (&&) true (List.map (fun e -> validate_value buf e value) conj_checks)
That's very helpful, Daniil. I will revise; thanks.

2021-06-13 21:18 UTC, jestabro commented
I'll run a final test before moving PR out of draft. Daniil's suggested revisions are implemented in the commit above
(9b593c2), making for much cleaner code.

2021-06-22 08:28 UTC, merged